### ISSUE TITLE
Support HeatMap

### ISSUE THREAD

**Issue by bhaskarvk** [bhaskarvk/leaflet.extras#1]
Options
- https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html / https://github.com/pa7/heatmap.js/tree/develop/plugins/leaflet-heatmap
- https://github.com/Leaflet/Leaflet.heat (This is from the Leaflet guys) 
- https://github.com/ursudio/webgl-heatmap-leaflet

I'm leaning towards #3 as it has performance benefits over the other two.

**Comment by bhaskarvk** [comment]
closed in 488de0682da81c1598d0b43eeb27d48983f39286

**Comment by RCura** [comment]
After trying a lot to use this library, I'm now convinced that it's not satisfying enough for a real use:

- The [original library](http://github.com/pyalot/webgl-heatmap) hasn't evolved in years ;
- some of the functions that probably worked years ago do not anymore, for example gradientTextures that doesn't work (heatmap remains black, check the original example), and thus doesn't allow to change the default colors ;
- `heatmap.blur()` and `heatmap.multiply()` can't be applied live : layer has to be removed, changed and added again.

In comparison, [Leaflet.heat](http://github.com/Leaflet/Leaflet.heat) is way more reliable, considering it's developed by Leaflet authors and more actively maintained.

As for the perfomances, I did some benchmark using the `feature/heatmap` branch of [rstudio/leaflet](http://github.com/rstudio/leaflet) and comparing it to this WebGLHeatmap binding, for different size datasets :
- `small` : 10k random points
- `medium` : 100k random points
- `big` : 500k random points

Here's the load speed :
<details>
<summary>Leaflet.heat vs webGLHeatmap</summary>

| Framework | Size | Time (s) |
|-----------|------|------|
| Leaflet.heat | Small | 1.14 |
| Leaflet.heat | Small | 1.14 |
| Leaflet.heat | Small | 1.16 |
| Leaflet.heat | Small | 1.20 |
| Leaflet.heat | Small | 1.13 |
|-----------|------|------|
| WebGLHeatmap | Small | 1.32 |
| WebGLHeatmap | Small | 1.35 |
| WebGLHeatmap | Small | 1.41 |
| WebGLHeatmap | Small | 1.38 |
| WebGLHeatmap | Small | 1.32 |
|-----------|------|------|
| Leaflet.heat | Medium | 1.60 |
| Leaflet.heat | Medium | 1.63 |
| Leaflet.heat | Medium | 1.65 |
| Leaflet.heat | Medium | 1.61 |
| Leaflet.heat | Medium | 1.68 |
|-----------|------|------|
| WebGLHeatmap | Medium | 1.70 |
| WebGLHeatmap | Medium | 1.83 |
| WebGLHeatmap | Medium | 1.83 |
| WebGLHeatmap | Medium | 2.23 |
| WebGLHeatmap | Medium | 2.19 |
|-----------|------|------|
| Leaflet.heat | Big | 3.23 |
| Leaflet.heat | Big | 3.17 |
| Leaflet.heat | Big | 3.22 |
| Leaflet.heat | Big | 3.29 |
| Leaflet.heat | Big | 3.23 |
|-----------|------|------|
| WebGLHeatmap | Big | 3.29 |
| WebGLHeatmap | Big | 3.17 |
| WebGLHeatmap | Big | 3.29 |
| WebGLHeatmap | Big | 3.21 |
| WebGLHeatmap | Big | 3.14 |

</details>

This shows that for such datasets, there is no significant differences in load time. I also checked memory use (js heap), and the result is also approximately the same.

For all those reasons, I'd like `Leaflet.heat` to be considered worthy of being added to `leaflet.extras`, as I think it would be a big asset for this package, and for R spatial analysts in general.

**Comment by bhaskarvk** [comment]
@RCura Thanks for the detailed comparison. I'll integrate leaflet.heat soon.

**Comment by bhaskarvk** [comment]
@RCura Some more comments
Recently I fixed some performance issues in the WebGL heatmap code (see #42), have you tried with the revised code for your benchmarking ? 
I know why gradientTextures doesn't work (CORS issue) and in theory should be fixable.

I will integrate Leaflet.heat but just wanted to make sure your benchmarking is done against the latest code base.

**Comment by RCura** [comment]
@bhaskarvk : I ran those tests like 2-3 days ago, and used the github version of leaflet.extras, so, this commit was taken into account :)

As for the gradientTextures, I'm glad you found :)
It seems to have been bugging for years (see that issue : pyalot/webgl-heatmap#7), and the author seems to have abandonned this repo ([this PR](https://github.com/pyalot/webgl-heatmap/pull/8) hasn't been answered in 1 year), so, I don't know how/if you want to correct it, but a fresh fork might be a good option :)

Thanks for your work 😀

**Comment by Vishan07** [comment]
Great to read that Leaflet.heat will be integrated. Do you have an expectation as to when this will be available?

**Comment by dutchminator** [comment]
I'd like to add my vote for integrating leaflet.heat. 
@bhaskarvk Do you have an ETA more specific than "soon" on when you will be able to implement it? Is there any way we can assist you with this?

**Comment by bhaskarvk** [comment]
I'll start working on this today, so hopefully before the start of next week.

**Comment by timelyportfolio** [comment]
@bhaskarvk, we were nearly finished integrating `leaflet.heat` https://github.com/rstudio/leaflet/tree/feature/heatmap a while back but ran into some problems with the underlying library, most specifically https://github.com/Leaflet/Leaflet.heat/pull/32https://github.com/Leaflet/Leaflet.heat/pull/32.  We were unwilling to run with a fork, so ultimately abandoned.

**Comment by bhaskarvk** [comment]
I know, hence my initial hesitation in integrating leaflet.heat. However I feel comfortable working off a fork for leaflet.extras. I have had to fork and fix quite a few of the plugins that have been integrated in this repo. Many times original authors abandon their projects but fixing small issues is no big deal.
I'll start my work based of the `leaflet.heat` branch and make sure to integrate that PR too.

**Comment by timelyportfolio** [comment]
Big difference here is the author is leaflet.heat is also the author of leaflet :)

**Comment by bhaskarvk** [comment]
Oh man you guys are killing me, that Leaflet.heat hasn't been touched by the owner in a while too and has a lot of pending PRs. So my first task is to fork it and merge the pending PRs (coz they contain some important fixes). This is going to take me a while (approx 1 or 2 weeks).

**Comment by bhaskarvk** [comment]
@timelyportfolio / @jcheng5 , Does this Leaflet/Leaflet.heat#43 look like a better alternative to Leaflet/Leaflet.heat#32, they kind of look like addressing the same problem, but 43 looks more exhaustive.

**Comment by jcheng5** [comment]
I'd be surprised if 78 strictly dominates 32--it makes the same mistake that master does, of adding together the altitudes instead of alpha blending them.

**Comment by bhaskarvk** [comment]
Yes I saw that, but w/o `max` I've no way to alpha blend. I need to see how to alpha blend on top of 78. Coz 78 is imp. too. There is a valid use case to support intensity using altitude.

**Comment by bhaskarvk** [comment]
never mind I think I know what to do.

**Comment by jcheng5** [comment]
78 removes the option for max intensity by auto assigning max intensity based on the data, is that right? Is that desirable behavior? I'd think you'd want the ability to be explicit.

**Comment by jcheng5** [comment]
By the way, IIRC by far the best results were by alpha blending and not performing clustering at all, and was still plenty fast for 10K data points (I don't think I tested larger).

**Comment by bhaskarvk** [comment]
For the `max` intensity, looks to me, if only Lat/Lng are supplied, it defaults to 1, and should be only provided if in addition to Lat/Lag you supply the actual intensity in the `alt` field. And 78 calculates appropriate max based on the intensity if provided. So I don't see a need for `max`, unless I am missing something obvious.

**Comment by bhaskarvk** [comment]
I don't understand `not performing clustering` at all. Are you talking about marker clustering, or something else ?

**Comment by bhaskarvk** [comment]
FWIW , here's my merged changes so far
https://github.com/Leaflet/Leaflet.heat/compare/gh-pages...bhaskarvk:up2date?expand=1

I've added your alpha blended code but commented it out for now, will test with and w/o it. From where I see I don't think alpha blending is required as the max is changed during the calculation. But we'll see.

**Comment by jcheng5** [comment]
I'm saying what if the max is not the max intensity of the data, but some other higher value. Like picture you have two data sets that are being plotted side by side (or two layers in the same map) that reflect the same type of data, and one of them has no points that reach the max?

(My PR used the intensity too btw, in case that wasn't clear. It just does a better job of combining multiple data points in the same cell IIRC.)

**Comment by bhaskarvk** [comment]
OK cool, I have my task cut out, I'll play with just your PR, just 78 and may be a combo of them.

**Comment by jcheng5** [comment]
Sorry to preface everything with IIRC but it's been a long time and I'm on my phone. So clustering refers to (IIRC) Leaflet.heat works pretty hard to reduce the number of points it sends to the underlying heatmap. This should just be a performance optimization as far as I could tell but the end result is the heatmap looks radically different depending on the factor (I think it's `v`?).

**Comment by bhaskarvk** [comment]
@RCura I have a small question, the timings that you mentioned in https://github.com/bhaskarvk/leaflet.extras/issues/1#issuecomment-270167199. 
How did you calculate them ? was it using `sys.time` or `proc.time` ? Coz if so then you're measuring only the R function execution time, and not the JS execution time. In that case the slight slowness in the R code of webglheatmap is expected because it builds the points in R so as to avoid an expensive computational `for` loop on the JS side.
If you have profiled only R code, please also profile JS part using chrome dev tools. I am very much interested in seeing how that compares.
I want to have both the libs available as options but want to make proper recommendations based on overall performance of the two.

Thanks

**Comment by RCura** [comment]
The benchmarks I gave are the js benchmarks, using chrome dev tools profiling :)
I didn't write any R benchmarks for the reasons you say, that I also noticed when first wanting to do this ^^

**Comment by bhaskarvk** [comment]
All done.
@RCura Some more notes....

- I've fixed the gradientTexture part in webgl-heatmap but it needs a weird hack of zooming-in zooming-out on map load to work. The hack is part of the binding JS so you don't have to do anything special. Just a small zoom-in zoom-out when the map loads initially will occur if you were to use the two available gradientTextures.

- You can work on both the webgl and the regular heatmap maps using `leafletProxy()` + `htmlwidgets::onRender()`, w/o needing to rebuild the whole heatmap.

So something like

```r

leaflet() %>% addHeatMap(..., layerId="ABC")  
# OR
leaflet() %>% addWebGLHeatMap(..., layerId="ABC")  

And later on 
leafletproxy() %>%
  htmlwidgets::onRender(JS("
    function(el, x, data) {
      var map = this;
      var layer = map.layerManager.getLayer("heatmap", "ABC");
      // OR
      var layer = map.layerManager.getLayer("webGLHeatmap", "ABC");

      // Work on layer using whatever JS operations it permits.
    }
  "))
```

- Finally for my satisfaction, could you run the same benchmarks again on the `addHeatmap` and `addWebGLHeatMap` functions in this package again? Please provide R function times, and JS load times. Also please run the tests for up to 2M points so 10K, 100K, 250K, 500K, 1M, 2M.
That would be really helpful to me.

**Comment by RCura** [comment]
Did all those benchmarks : the result is no good for WebGLHeatmap ;)

Here's [the gist with all infos](https://gist.github.com/RCura/701f7e1bd7482a262e3f643d5f227bc6).
addHeatmap and addWebGLHeatmap have similar performances while creating the htmlwidget :
<details>
<summary>Code</summary>

    heat_benchs <- microbenchmark(
        heat_10k = leaflet() %>% addHeatmap(data = coords_10k, layerId = "ABC"),
        webgl_10k = leaflet() %>% addWebGLHeatmap(data = coords_10k, layerId = "ABC"),
        heat_100k = leaflet() %>% addHeatmap(data = coords_100k, layerId = "ABC"),
        webgl_100k = leaflet() %>% addWebGLHeatmap(data = coords_100k, layerId = "ABC"),
        heat_250k = leaflet() %>% addHeatmap(data = coords_250k, layerId = "ABC"),
        webgl_250k = leaflet() %>% addWebGLHeatmap(data = coords_250k, layerId = "ABC"),
        heat_500k = leaflet() %>% addHeatmap(data = coords_500k, layerId = "ABC"),
        webgl_500k = leaflet() %>% addWebGLHeatmap(data = coords_500k, layerId = "ABC"),
        heat_1M = leaflet() %>% addHeatmap(data = coords_1M, layerId = "ABC"),
        webgl_1M = leaflet() %>% addWebGLHeatmap(data = coords_1M, layerId = "ABC"),
        heat_2M = leaflet() %>% addHeatmap(data = coords_2M, layerId = "ABC"),
        webgl_2M = leaflet() %>% addWebGLHeatmap(data = coords_2M, layerId = "ABC"),
        times = 100
    )

</details>

(Run 100 times with `microbenchmark` the lesser the better)

![bench_r](https://cloud.githubusercontent.com/assets/807703/22656064/646ab186-ec92-11e6-9279-1a39ef5b8c0d.png)

But page load shows some very different performances, webgl becoming massively slow as points number is increased :

<details>
<summary>wbench Code</summary>

    http-server -p 8080 &
    wbench http://localhost:8080/heat_10k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/webgl_10k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/heat_100k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/webgl_100k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/heat_250k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/webgl_250k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/heat_500k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/webgl_500k.html -nc >> benchs.txt &&
    wbench http://localhost:8080/heat_1M.html -nc >> benchs.txt &&
    wbench http://localhost:8080/webgl_1M.html -nc >> benchs.txt &&
    wbench http://localhost:8080/heat_2M.html -nc >> benchs.txt &&
    wbench http://localhost:8080/webgl_2M.html -nc >> benchs.txt &&
    pkill node

</details>

(the lesser the better)
![bench_js](https://cloud.githubusercontent.com/assets/807703/22656087/7ca451b2-ec92-11e6-97ff-82d3a8494dde.png)

File size are quite the same, so, this can't be a file loading difference.
Please note that the 1M and 2M benchmarks were'nt done as the smaller ones : htmlwidgets::saveWidget fails at saving those, so, I had to knit the pages. The size and load time is increased, but this has been done both for addHeatmap and addWebGLHeatmap.

So, seems there's a clear winner ;)

**Comment by bhaskarvk** [comment]
Wow I would never have guessed webGL plugin would be this bad. Thanks for all your hard work on this btw.
