### ISSUE TITLE
devtools::install('rstudio/leaflet')

### ISSUE THREAD

**Issue by nelsonSchwarz** [bhaskarvk/leaflet.extras#10]
Perhaps a small correction, but:
`devtools::install('rstudio/leaflet')` should be
`devtools::install_github('rstudio/leaflet')` right?

I wasted at least a full minute troubleshooting XD

**Comment by bhaskarvk** [comment]
Thanks for the catch, fixed!

**Comment by pssguy** [comment]
still incorrect in README.md file

**Comment by bhaskarvk** [comment]
Yikes, I had fixed it and broke it again when I reworked the Readme.
