### ISSUE TITLE
hyperlinks into maps

### ISSUE THREAD

**Issue by richardbeare** [bhaskarvk/leaflet.extras#101]
Hi,
I've asked this on the leaflet issue page, but thought you might have insights as well.

I have a lot of markers and I'd like to be able to create a table of links that trigger zooms to a specific marker. Various stackoverflow comments (https://stackoverflow.com/questions/25340051/leaflet-zoom-onto-location-using-link-and-map-setview) suggest that it is possible with base leaflet, but I'd like to add this capability to pages currently generated from Rmd. I'm happy to handcraft some html and javascript, but don't know my way around js/leaflet to get started.

I think I need to construct a link which triggers a call to setView, but don't know how to set up the names I need.

Any advice appreciated.

Thanks

**Comment by bhaskarvk** [comment]
https://github.com/rstudio/leaflet/issues/460
