### ISSUE TITLE
Leaflet.MarkerCluster.LayerSupport

### ISSUE THREAD

**Issue by kent37** [bhaskarvk/leaflet.extras#11]
Marker clusters alone don't work well with layers and the layer menu. The marker clusters should update as layers are turned on and off, but they don't. This plugin claims to fix that.
https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport

**Comment by bhaskarvk** [comment]
Already merged in leaflet trunk.
https://github.com/rstudio/leaflet/pull/293/commits/b6c980d5ade6729af0f4e7712397a114cb8dd30d
e.g.
http://rpubs.com/bhaskarvk/leaflet-marker-clusterming

**Comment by kent37** [comment]
Sweet! Thanks!
