### ISSUE TITLE
[plugin request] graticule with label

### ISSUE THREAD

**Issue by dracodoc** [bhaskarvk/leaflet.extras#113]
The existing `graticule` support in leaflet doesn't show label, which make it less useful. [This plugin](https://github.com/cloudybay/leaflet.latlng-graticule) draw labeled graticule in a canvas.

If the canvas method is not optimal, the parameter `options = pathOptions(pointerEvents = "none", clickable = FALSE)` of existing `graticule` make me wonder if we can have some pop ups when grid lines was clicked.

**Comment by bhaskarvk** [comment]
I already have simple graticule plugin which does support labels, it won't work w/ non spherical mercator projections, but if you're just sticking to the default projection, may be that will suffice. http://rpubs.com/bhaskarvk/leaflet-simplegraticule

**Comment by dracodoc** [comment]
This should be good enough for my need, thanks!

Is this introduced in anywhere? I read rstudio document, the readme of this repo but didn't know about this. It's in leaflet examples but not documented?
