### ISSUE TITLE
Any chance of providing support for Leaflet.extra-markers?

### ISSUE THREAD

**Issue by goshevs** [bhaskarvk/leaflet.extras#116]
Just wondering whether you plan to add support for Leaflet.extra-markers in the near future? Thank you.

**Comment by bhaskarvk** [comment]
That's a based on Awesome markers which are already supported in Leaflet core. The only extra icons you get in Extra-Markers are Symantic UI icons. I  not sure if that warrents including the plugin in leaflet.extras. But feel free to sumit a PR. You can use the code for Awesome Markers in the leaflet pkg or Weather icons i n this package as a starting point.
