### ISSUE TITLE
How to Recolor An Already Existing Polygon

### ISSUE THREAD

**Issue by jrisi256** [bhaskarvk/leaflet.extras#122]
Hi! Thanks for creating this wonderful library! I do have an issue though.

Currently I have shapefiles for all counties for all 50 states. And I am coloring them based on some outcome variable chosen by the user (e.g. unemployment, poverty rate, etc.)

Using leafletProxy() I can update the color however this necessitates a redrawing of the polygons even though it is the same polygons being drawn over and over again! I just want to change the color.

Normally, this wouldn't be an issue, but because it is a relatively large collection of shapefiles it can take a bit before the map updates.

I was wondering if there was any plans in the work to add functionality for editing an already existing set of polygons or something along those lines? If not, what would you recommend I do? (I've already reduced the shapefiles down in size as much as possible). 

https://stackoverflow.com/questions/15606027/dynamically-change-the-color-of-a-polygon-in-leaflet

The above stackoverflow post seems to suggest the setStyle() in the Javascript version of Leaflet would cover my problem. Does setStyle() like functionality exist already in leaflet.extras that I am not aware of? Would it be easy to add? I unfortunately don't know Javascript otherwise I would attempt a solution myself.

Thanks again!

**Comment by timelyportfolio** [comment]
@jrisi256, I understand that sometimes it is difficult to know where best to pose a question, but please try not to crosspost, and if you do crosspost, please include a link to all crossposts.  I believe this is much better placed in https://github.com/rstudio/leaflet/issues/496, so will close here.  If unanswered there, we can reopen and potentially discuss here.

**Comment by jrisi256** [comment]
Sorry! Duly noted for next time.
