### ISSUE TITLE
Leaflet map search button NOT work 

### ISSUE THREAD

**Issue by yzjiangyang** [bhaskarvk/leaflet.extras#135]
"# We need latest leaflet package from Github, as CRAN package is too old.
devtools::install_github('rstudio/leaflet')
devtools::install_github('bhaskarvk/leaflet.extras')"

Hi, I was able to use these 2 packages to search the markers on the map. Did you update the packages recently? I just installed them on my new computer again, but the search button does not work now.
Thank you!
![qq 20180416021225](https://user-images.githubusercontent.com/10675190/38781658-2818052e-411b-11e8-883e-909d4288dfe4.png)

**Comment by schloerke** [comment]
@yzjiangyang  do you have a code example?

**Comment by schloerke** [comment]
Found in the error in code inst/examples/search.R example.

**Comment by schloerke** [comment]
Ok... good news. 

Example is fixed when using circles and not circlemarkers as circlemarkers don't have the method `.getBounds()`. Makes sense as their width is in pixels... not meters on the map.  

I've updated the example in a final PR.

http://leafletjs.com/reference-1.3.0.html#circle-getbounds

**Comment by schloerke** [comment]
Fixed in #136 Closing

**Comment by yzjiangyang** [comment]
Hi,
If use circles, search button works, but after zoom in the map, the points on maps get much bigger.
I prefer using circlemarkers, but search button does not work, Will you solve this issue?
Thank you
