### ISSUE TITLE
Feature request: support for CRS Tiles and fitBounds for non-geographical

### ISSUE THREAD

**Issue by jamesdalg** [bhaskarvk/leaflet.extras#142]
I've been working for a while to get leaflet to work with CRS coordinates. If there could be some way of doing this that works, perhaps with a new function that overrides hardcoded functions (https://github.com/rstudio/leaflet/issues/541,https://github.com/rstudio/leaflet/issues/371) to correctly set bounds in a nongeographical way, you would open up leaflet to so many users who want to use leaflet plugins like zoomify, deepzoom, gdal2tiles-leaflet, etc. see https://leafletjs.com/plugins.html#non-map-base-layers).  Currently R lacks this functionality and it would allow anyone who wanted to display a large image (e.g. microscopy, huge plots for big data) to do so.

**Comment by bhaskarvk** [comment]
Added my comments in the cross posted issue. Closing this one.
