### ISSUE TITLE
Please add zoomhome plugin

### ISSUE THREAD

**Issue by psalmody** [bhaskarvk/leaflet.extras#161]
Didn't see this plugin mentioned, but I would love to use it in my Shiny/R applications.

https://github.com/torfsen/leaflet.zoomhome

:-D Thanks!!

**Comment by tim-salabim** [comment]
have you seen `mapview::addHomeButton()`?

**Comment by tim-salabim** [comment]
If you need it to be extended in any way, just open an issue at https://github.com/r-spatial/mapview/issues
