### ISSUE TITLE
Polyline Offset

### ISSUE THREAD

**Issue by fermumen** [bhaskarvk/leaflet.extras#170]
Hi, 
A while ago I created a forked version of Leaflet to include a plugin that I was interested in. 
plugin: https://github.com/bbecquet/Leaflet.PolylineOffset
forked Leaflet: https://github.com/fermumen/leaflet

I was hoping I could add it to leaflet.extras or perhaps as a different package. The main issue is that as it is right now it modifies de the function addPolyline(). I'd appreciate some pointers on the best way to do this.

Best,
Fernando

**Comment by trafficonese** [comment]
Should this be closed here, since there is this [PR](https://github.com/rstudio/leaflet/pull/614) for Leaflet directly?
