### ISSUE TITLE
Draw: no event capture yet?

### ISSUE THREAD

**Issue by mbacou** [bhaskarvk/leaflet.extras#19]
Hi,
I'm a little confused between this version of leaflet.draw and the branch here https://github.com/rstudio/leaflet/tree/draw-toolbar. Which one do I need to follow?

I'm trying to capture X,Y coordinates from drawn markers. Is this implemented (even roughly)?

Many thanks.

**Comment by bhaskarvk** [comment]
It is implemented. I will setup a shiny example soon. This version is more up to date and feature complete than the leaflet branch.

**Comment by mbacou** [comment]
Ha, very good thanks! Will give it another try.
I have a similar question about using `input$map_marker_dragend` events (trying to capture the location of a circle marker after dragging). I found @byzheng  example here https://gist.github.com/byzheng/a7ed2057b51e425e309c and installed his fork of leaflet, but these events don't seem to fire.

**Comment by bhaskarvk** [comment]
I've implemented event listeners for the created/edited/deleted events. I haven't coded the others. I can easily do that, but if you're interested in capturing locations of features after dragging, you're better off listening to the edited event.
The dragged events are transitionary and one can easily cancel the operation and then you'll have to revert back.

For the edited event you can listen on input$<map_id>_draw_edited_features event.

**Comment by mbacou** [comment]
You mean listening to `input$draw_edited_features` -- with `draw` the layerId of the drawToolbar()? Using `input$_draw_edited_features` crashed Shiny.

**Comment by bhaskarvk** [comment]
`input$<mapid>_draw_edited_features` where <mapid> is your leafletOutput element ID.

**Comment by mbacou** [comment]
OK, that works perfect. Thanks.
