### ISSUE TITLE
Support Leaflet.draw

### ISSUE THREAD

**Issue by RCura** [bhaskarvk/leaflet.extras#2]
Would be really usefull, especially in combination with shiny and others interactive frameworks.
[Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) is a [recommanded plugin](http://leafletjs.com/plugins.html#edit-geometries) from Leaflet, and has already been partially integred in [rstudio's leaflet](https://github.com/rstudio/leaflet) package ([draw-toolbar](https://github.com/rstudio/leaflet/tree/draw-toolbar) branch).
More recently, it's been fixed/updated in @ssoulier [fork](https://github.com/ssoulier/leaflet), and updated/upgraded in [mine](https://github.com/RCura/leaflet), which is, AFAIK, the only one currently working.

It's not that difficult to include, but the hard part is that it's currently conflictual with Leaflet.heat (even in pure js versions, without using R), couldn't figure out why (probably some conflicted-name functions like draw()).

Anyway, that would be a really usefull addition to this leaflet plugins package, as the spatial selection/drawing still remains the weak part of R spatial toolset.

**Comment by RCura** [comment]
Another problem I encoutered.
The drawn features are passed to R as GeoJSON, which works well for all geoms (lines, points etc.) except the circles that can be drawn : as GeoJSON doesn't handle such geoms, they can't be properly read/updated in R, only their centers are understood and not their radius. See [this discussion on shiny mailing-list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/K-YZAJ20TRw/1haJf9VGCQAJ) for more details.

**Comment by bhaskarvk** [comment]
Closing as duplicate, tracking under bhaskarvk/leaflet.extras#2

**Comment by bhaskarvk** [comment]
Also see rstudio/leaflet#277 , rstudio/leaflet#188

**Comment by bhaskarvk** [comment]
Done in 1a5be1e.

**Comment by timelyportfolio** [comment]
This works beautifully for me except with `editOptions = TRUE`.  I will try to debug, but for now here is a very simple reproducible example.

```
library(leaflet)
library(leaflet.extras)

leaflet() %>%
 addTiles %>% # errors with or without addTiles
 addDrawToolbar(editOptions = TRUE)
```

The error I get in the JavaScript console.

```
Uncaught Error: options.featureGroup must be a L.FeatureGroup
    at e.initialize [as _initialize] (EditToolbar.Edit.js:22)
    at e.initialize (Leaflet.draw.drag-src.js:577)
    at new e (leaflet.js:6)
    at e.getModeHandlers (EditToolbar.js:61)
    at e.addToolbar (Toolbar.js:83)
    at e.addToolbar (EditToolbar.js:98)
    at e.onAdd (Control.Draw.js:58)
    at e.addTo (leaflet.js:9)
    at e.<anonymous> (draw-bindings.js:71)
    at e.LeafletWidget.methods.addDrawToolbar (draw-bindings.js:141)
```

or as a screenshot

![image](https://cloud.githubusercontent.com/assets/837910/21735240/e085bd42-d42d-11e6-8f2b-cf2846621c1f.png)

**Comment by timelyportfolio** [comment]
Never mind, I figured it out (sorry!).

```
leaflet() %>%
  addTiles() %>%
  addDrawToolbar(editOptions = editToolbarOptions())
```
