### ISSUE TITLE
add L.Control.Rose plugin

### ISSUE THREAD

**Issue by MaelTheuliere** [bhaskarvk/leaflet.extras#200]
I see no alternative to add north arrow to a leaflet map.
Link to the plugin https://github.com/bradhamson/L.Control.Rose

**Comment by tim-salabim** [comment]
Two things:

a) why? North is always up in mercator
b) this repo is pretty much dead. Alternative is https://github.com/trafficonese/leaflet.extras2

**Comment by MaelTheuliere** [comment]
Thanks for your quick feedback. My answer : 
a) because users asked for it (I share your point of view however !), especially for png export of interactive map
b) ok, i will put this issue on the new repo, sorry :-)
