### ISSUE TITLE
Changing white squares at the end of vertex

### ISSUE THREAD

**Issue by Camil88** [bhaskarvk/leaflet.extras#207]
Hi, I try to change somehow white squares at the end of each vertex (when I  draw a polygon). `lineCap` and `lineJoin` don't make a job. Honestly, those white squares look terrible. Is there any chance to change those white squares at all? Shape/size/color?

**Comment by Falke-Design** [comment]
If you mean the squares from Leaflet-Draw look into: https://stackoverflow.com/a/63939495/8283938

**Comment by Camil88** [comment]
Thanks, it works fine:)
