### ISSUE TITLE
Feature Request: Implement the Drawing Tool Leaflet-Geoman

### ISSUE THREAD

**Issue by Falke-Design** [bhaskarvk/leaflet.extras#208]
Hi,

I'm one of the maintainer of [Leaflet-Geoman](https://github.com/geoman-io/leaflet-geoman) and we want to ask, what is needed that it works with ` Leaflet R` and will be implemented here?

**Why should it implemented?**
[Leaflet-Geoman](https://github.com/geoman-io/leaflet-geoman) is a more modern drawing / editing tool then [Leaflet.Draw](https://github.com/Leaflet/Leaflet.draw). Leaflet.Draw is [not longer maintained](https://github.com/Leaflet/Leaflet/issues/7545) and has many outstanding issues. Leaflet-Geoman instead releases continuously new features and fixes issues very quickly.

**Comment by tim-salabim** [comment]
Hi @Falke-Design you can contribute to [leafpm](https://github.com/r-spatial/leafpm) which is maintained by @timelyportfolio and hosted under the [r-spatial](https://github.com/r-spatial) organisation. Similar to Leaflet.Draw leaflet.extras is no longer (rpoperly) maintained.

**Comment by Falke-Design** [comment]
Thanks for the fast replay. I created a new Issue on leafpm.
