### ISSUE TITLE
Merge other plugins I developed

### ISSUE THREAD

**Issue by byzheng** [bhaskarvk/leaflet.extras#3]
Hi Bhaskar,

I have developed a few plugins for leaflet packages (https://github.com/byzheng/leafletplugins), but have limited time to maintain them.

I am happy to contribute them to your package if you think they are useful and interesting. 

Cheers,
Bangyou

**Comment by bhaskarvk** [comment]
Thanks Bangyou. I would be happy to move them over to leaflet.extras. I'll take a look at your package and merge here.

**Comment by bhaskarvk** [comment]
PRs #14, #15, and #16.

**Comment by bhaskarvk** [comment]
GPS and Search have been merged. ChineseBaseMaps will be in milestone two.
