### ISSUE TITLE
Search button plugin

### ISSUE THREAD

**Issue by adrfantini** [bhaskarvk/leaflet.extras#32]
According to this stackOverflow question:
http://stackoverflow.com/questions/37798690/search-button-for-leaflet-r-map

search buttons for leaflet can be implemented, but I cannot find the package `leafletplugins` anymore. Can this be provided by `leaflet.extras`?

**Comment by bhaskarvk** [comment]
Yes it's on my TODO list.

**Comment by bhaskarvk** [comment]
Already being tracked in #15. So closing this and tracking it there.

**Comment by bhaskarvk** [comment]
Now in trunk. Demo http://rpubs.com/bhaskarvk/leaflet-search
