### ISSUE TITLE
Esri leaflet

### ISSUE THREAD

**Issue by steveputman** [bhaskarvk/leaflet.extras#4]
Hi--assuming licensing issues can be dealt with, consider this a request for Esri Leaflet http://esri.github.io/esri-leaflet

Thanks for the great package!

Steve

**Comment by bhaskarvk** [comment]
Thanks Steve. Esri package is a beast but it's on my radar, but it will take some time :)

**Comment by bhaskarvk** [comment]
Tracking this in https://github.com/bhaskarvk/leaflet.esri. ESRI is too huge to include in leaflet.extras, it needs its dedicated plugin.

**Comment by steveputman** [comment]
Thanks so much for spending the time on this, Bhaskar.

**Comment by bhaskarvk** [comment]
I'll keep this open till I have a initial feature set built out.

**Comment by bhaskarvk** [comment]
Closing this, as leaflet.esri has come a long way and become an independent project.
