### ISSUE TITLE
Get the layer_id after adding an existing features into draw plugin

### ISSUE THREAD

**Issue by byzheng** [bhaskarvk/leaflet.extras#40]
In my case, I need to add a few existing features into the draw plugin and get the layer id to store some variables. 

For example, I can use codes below to create a polygon. Is there any ways to get the id from a layer? 

library(leaflet.extras)
    lat <- c(1, 2, 2, 1)
    lng <- c(1, 1, 2, 2)
    map <- leaflet() %>% 
        addDrawToolbar(targetGroup = 'drawGroup', 
                       editOptions = editToolbarOptions()) %>% 
        addPolygons(lat = lat, lng = lng, group = 'drawGroup')
    map

**Comment by bhaskarvk** [comment]
You have two options.
a) Assign layerIds as part of `addPolygons` call. You'll need to supply a vector of unique layerIds with length equal to number of polygons/polylines/markers. These will be the unique IDs and you'll get them back as part of the data returned from the `Shiny.onInputChange` events.
b) If you don't supply any layerID, then if you edit a polygon (move/drag/resize) then a unique layerID will be added to those geometries that you've edited, and again you'll be able to get that back as part of the Shiny event.

**Comment by byzheng** [comment]
I prefer to use option a. Do you know which event I should use?

**Comment by bhaskarvk** [comment]
As per my latest commit today, these are the events captured and a Shiny event is emitted for them.

```
L.Draw.Event.DRAWSTART
L.Draw.Event.DRAWSTOP
L.Draw.Event.CREATED
L.Draw.Event.EDITSTART
L.Draw.Event.EDITSTOP
L.Draw.Event.EDITED
L.Draw.Event.DELETESTART
L.Draw.Event.DELETESTOP
L.Draw.Event.DELETED
```

The event you should capture in Shiny depends on what action was performed.  If I get some free time next week I'll try and set up a demo shiny app.

**Comment by byzheng** [comment]
I guess we have some confusing here. I plan to retrieve the layer id after addPolygon is called, before any draw related action is performed (i.e. when a map is loaded). The list of event above is triggered when any action is called in draw. 

For my testing with js event, shiny:inputchanged, there are only four events `mymap_bounds`, `mymap_center`, `mymap_zoom` and `mymap_groups` when a map is loaded. 

See this gist for an example.

This question may be related with leaflet package. The get a layer id by layer and/or group

**Comment by bhaskarvk** [comment]
You can listen on map.id+ 'shape_mouseover' / 'shape_mouseout' / 'shape_click' events. But even in that case at least one of those events (i.e. mouseover/mouseout/click on a polygon) needs to happen for the event to trigger.
You can see the details at https://github.com/rstudio/leaflet/blob/master/javascript/src/methods.js#L338

Also you have access to 'map.layerManager' it stores added features by ID/group/stamp( Leaflet assigned ID) etc.
https://github.com/rstudio/leaflet/blob/master/javascript/src/layer-manager.js. You can use that to capture the layerId is `htmlwidgets::onRender` call. I have something like that in http://rpubs.com/bhaskarvk/leaflet-minimap.

**Comment by byzheng** [comment]
Sorry to open discussion this question again. I am trying to write some js codes to get the layerId and _leaflet_id from drawItem group. I noticed there is an function `getDrawnItems` in the `draw-binding.js`. It seems what I need. But my question is how could I return the results into R?

**Comment by bhaskarvk** [comment]
The `getDrawnItems` will not give you IDs if none were assigned in the first place.

Btw there are two types of IDs, so let's clear out that thing first.

a) `layerID` assigned by the caller (you) when you pass a vector of layerIDs equal to the number of polygons you have in the `addPolygons` call. In this case you don't need these back as you have assigned them yourself, so you already know which layerID maps to which polygon. 

If you don't supply layerID as part of your `addPolygons` call then none will be generated. So in this case there is nothing to get back as no layerIDs were supplied.

2) `stamp` this is a value generated for each layer (polygon in this case) using `L.stamp` call. There is a `LayerManager` https://github.com/rstudio/leaflet/blob/master/javascript/src/layer-manager.js which is stored in the `map` JS object under `map.layerManger`. It stores layer<->stamp, layer<->group, layer<->layerID (if provided), layer<->category mappings.
You should be able to access it from `onRender`. So in your case you can easily do something like

```r
leaflet() %>%
addPolygons(data=data,....) %>%
htmlwidgets::onRender(JS("
    function(el, x, data){
        var map = this;
        Shiny.onInputChange(map.id+'_layers_added',map.layerManager);
    }"))
```

Then you can capture `map.id`+`_layers_added` on Shiny side and retrieve all the layers (polygons in your case) that were added and the stamp on them. Mind you they will not have a `layerID` if hadn't provided them in the `addPolygons` call.

**Comment by byzheng** [comment]
I think I overlook at my question. It is not necessary to obtain the layerId from draw group. The major target to obtain the layerID or leaflet is to link with other data in R. 

In the current codes, draw plugin is returned the _layer_id at the several events. If we return the layerId too at edit and delete events if exists, we can use this name to perform other operations.

 I can implement it later.
