### ISSUE TITLE
Question: webGLHeatmap.R

### ISSUE THREAD

**Issue by nelsonSchwarz** [bhaskarvk/leaflet.extras#42]
Hi Bhaskar, 

Thanks for your amazing work. Could you spare some time for feedback? 

I have deployed a Shiny app that uses the webGLHeatmap. The rendering of the map + heatmap is way too slow. It tries to renders 45MB of data. Is this too large? Is there a way to speed up the rendering.

Best, 
Nelson

**Comment by bhaskarvk** [comment]
Could you quantify the 'way too slow' part ?
https://github.com/bhaskarvk/UKCrime has crimeMap.html which is 67MB, it renders fine on my MacPro 2015 (16GB RAM). It's not super fast but I think it performs adequately considering that it's plotting about 500K points per layer (total ~ 3.5 Million points in 7 layers).

If it's possible could you share your code and data ? Also details about your computer, like CPU/GPU/Mem etc. as well as browser name/version. If possible, load up chrome devtool and profile the page loading. Also if you're using SpatialPointsDataFrame, trim the data, as you don't really need anything besides lat/lon for heatmap.

**Comment by nelsonSchwarz** [comment]
Sorry for the vagueness.

My shiny app has three views. Two of them run fine. The Virginia & Maryland view is the problem. That map uses a file which has different parts. If I remove everything and only leave lat / lon pairs—I am not using SpatialPointsDataFrames—it is actually 22 MB as an .RDS and 27 MB in memory. Not huge, right?

However, loading and interacting with the map is eternal. I am currently running the app on a free shinyapps.io server; I don't exactly know the specs for free servers, but it is likely nothing impressive. 

Please take a look at [a simplified version of my shiny app](https://mogean.shinyapps.io/simple_onlyheatmap/). Unfortunately, I cannot explain the context of the data, but the app should be enough.

This is how I am using rendering the leaflet in `server.R`

    output$heatmap <- renderLeaflet({
        data <- getData() 

        L <- leaflet(data) %>%
          addProviderTiles("CartoDB.Positron") %>%
          addWebGLHeatmap(~longitude, ~latitude,
                          opacity = getOpacity(), 
                          alphaRange = 0.25,
                          size = getResolution(), units = 'm')

        L
    })

**Comment by bhaskarvk** [comment]
How many points are being plotted in the VA/MD map ?
Could you share the data (Just the lat/lon) coordinates?
I don't think this is an issue with shinyserver spec. I JS performance with large # of points gets progressively worse, hence I'm curious to know how many points are you plotting.

**Comment by nelsonSchwarz** [comment]
1,743,527 points

**Comment by harryprince** [comment]
to console the heatmap range is so tough for me ..However, I am so excited that all you guys do this great job and make map data visulization is much easier more !

I can just plot by few lines code.
```
trips %>%
  leaflet() %>%
  setView(lng = 116.30, lat = 40.03, zoom = 12) %>%
  addTiles() %>%
ddWebGLHeatmap(lng=~X,
                                 lat=~Y,
                                 alphaRange = c(0.2:1),
                                 size = 200)# %>% addLegend(color=)
```

**Comment by nelsonSchwarz** [comment]
Do you still need me to share the data, @bhaskarvk?

**Comment by bhaskarvk** [comment]
@nelsonSchwarz with these many points the performance is indeed going to be very bad. I've been able to plot < 1M points successfully. But if you could please do share the data, I might try some performance improvements. But it is always possible that you've hit the upper end of WebGL performance too. Normal non-webGL layers tend to boggle down roughly after 50K points, so webGL is much better that way, but it will still have its limitations.
Do share the data and I can take a look.

**Comment by bhaskarvk** [comment]
Upon closer examination of my JS binding code I do see some room for performance improvements. I'll get you a new build in a day or two to try.

**Comment by nelsonSchwarz** [comment]
That sounds great! I really appreciate it. 

Here is [a link for the data; just the lat / lon. ](https://s3.amazonaws.com/rstudio-analysis/shiny-app-share/virginia.rds)

Let me know if I can help in any way.

**Comment by bhaskarvk** [comment]
@nelsonSchwarz try now, it's much faster. for 1.7M points it still is going to be slow, but now it completes under 5 secs on my Macpro.

**Comment by nelsonSchwarz** [comment]
Thank you so much!

**Comment by bhaskarvk** [comment]
You're welcome! Is it working now at acceptable speed/performance for you ?

**Comment by nelsonSchwarz** [comment]
Well, locally yes. But when I deploy to shiny, it seems to be as slow as
before. Can shiny install from GitHub?

**Comment by bhaskarvk** [comment]
The only overhead shiny should add is the time it takes to download the dataset. Is it possible for you to profile the shiny app and the web session (using chrome devtools) ?

**Comment by nelsonSchwarz** [comment]
I won't be able to get to that soon. But when I do, I'll make sure to reply.
