### ISSUE TITLE
Blur and radius in heatmap

### ISSUE THREAD

**Issue by Vishan07** [bhaskarvk/leaflet.extras#48]
Hi, I have a question about the Heatmap functionality in this package. 
In this issue on the leaflet page: https://github.com/rstudio/leaflet/pull/174 there is an option to provide the blur and radius for the heatmap, this makes them much nicer.
However, this is not available in the leaflet.extras package. Is there any way to give in these arguments?

If not, is there any way in which I will be able to use  'addHeatmap' function as described in the closed issue?

Thank you in advance!

**Comment by bhaskarvk** [comment]
I am using a different plugin and that one doesn't have these options. However I will integrate the Leaflet.heat plugin soon and you will be able to use `addHeatmap` along with those options.
Closing this as there is already an issue to track Leaflet.heat #1
