### ISSUE TITLE
Drawing polygons and retrieve the coordinates

### ISSUE THREAD

**Issue by Eltisho** [bhaskarvk/leaflet.extras#49]
Hi!
I'm new here and i'm francophone, so sorry if the question is not clear but i'll try to be clear as much as possible!

I'm doing a survey with Shiny on R where people have to draw polygons on map to show where they sampled. I'm using leaflet.draw to draw the polygons, but i can't manage to retrieve the coordinates of every polygons. I've searched a lot on internet but i can't find anything on it. 

So i would like people to be able to draw polygons, edit them, i would want my shiny app to save the coordinate of the polygon. 

Thank you!

**Comment by timelyportfolio** [comment]
@Eltisho, see if this helps https://github.com/timelyportfolio/leaflet/blob/master/inst/examples/gadget_draw2.R.  We have started working on a RConsortium project to assist with tasks like you mention, so I'll be sure to update this issue as we progress.

**Comment by bhaskarvk** [comment]
@Eltisho to add to what @timelyportfolio said, this is very straight forward, The draw plugin emmits several events which you can capture in shiny.
You can see all the events it emits in the source file https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/htmlwidgets/lib/draw/draw-bindings.js#L73

All you need to do is catch them in shiny as described in https://rstudio.github.io/leaflet/shiny.html under Input/Events section.

All the best!
