### ISSUE TITLE
Add a legend for the WMS tile 

### ISSUE THREAD

**Issue by bhaskarvk** [bhaskarvk/leaflet.extras#5]
_From @para2x on October 22, 2016 23:27_

Hi there, 
I was wondering if there is there anyway we can add the legend for the WMSTiles ?
Thanks

_Copied from original issue: rstudio/leaflet#312_

**Comment by bhaskarvk** [comment]
Is there an example I can look at? doesn't the existing addLegend work for you?

**Comment by bhaskarvk** [comment]
_From @para2x on October 24, 2016 0:10_

No, there is no explicit variable you can pass to the legend function for values and etc.
This an example of plug-in that creates a legend for WMS :
https://github.com/kartoza/leaflet-wms-legend

**Comment by bhaskarvk** [comment]
Ah OK a plugin, I think I can integrate it in my [leaflet.extras](https://www.github.com/bhaskarvk/leaflet.extras) package.

**Comment by para2x** [comment]
This is just great! I had not seen your package before. I'm sorry but if you thinking about adding more functionality to leaflet, I think "TimeDimension" is what is really missing. Something like this example
http://apps.socib.es/Leaflet.TimeDimension/examples/example13.html

**Comment by bhaskarvk** [comment]
Yes I have a bunch of plugins planned, but it's going to take some time. The WMS Layer is very easy to add, TimeDimension not so. :)

**Comment by bhaskarvk** [comment]
@para2x See https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/examples/wmsLegend.R. You will need to install leaflet using `devtools::install_github('rstudio/leaflet')` to use leaflet.extras

**Comment by steven224** [comment]
Dear @bhaskarvk 

I saw your wonderful video in youtube which you visualize data by using R+leaflet+Timedimension.
I am trying to do something same as what you did in video.
But it seems like I can't find time-dimension function in leaflet.extras.
May I know is this feature already published? where can I find the newest version of leaflet.extras?
Really appreciate the great library developed

**Comment by bhaskarvk** [comment]
@steven224 I have a half baked version in a private branch which is not ready to be commited to the master branch yet. I am very  much tied up in day job for Q1 2018. I hope to get back to doing some leaflet development in Q2 2018. Thanks.
