### ISSUE TITLE
Leaflet.extra package installing error

### ISSUE THREAD

**Issue by WandaB** [bhaskarvk/leaflet.extras#50]
```
devtools::install_github('bhaskarvk/leaflet.extras')
Downloading GitHub repo bhaskarvk/leaflet.extras@master
from URL https://api.github.com/repos/bhaskarvk/leaflet.extras/zipball/master
Installing leaflet.extras
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Kiddo/AppData/Local/Temp/RtmpWsZ8Q4/devtools22982d6b714e/bhaskarvk-leaflet.extras-3558bfe"  \
  --library="C:/Users/Kiddo/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'leaflet.extras' ...
** R
** inst
** preparing package for lazy loading
Error : package 'leaflet' 1.0.1 was found, but >= 1.0.2.9008 is required by 'leaflet.extras'
ERROR: lazy loading failed for package 'leaflet.extras'
* removing 'C:/Users/Kiddo/Documents/R/win-library/3.3/leaflet.extras'
Error: Command failed (1)
```

**Comment by bhaskarvk** [comment]
So as discussed on twitter, you need to install the latest `leaflet` package from GH before you can install `leaflet.extras`.

`devtools::install_github('rstudio/leaflet')`,  As per our twitter conv. I think you got some error while doing this for the httpuv pacakge.

So try this in order

```r
devtools::install_github('rstudio/httpuv')
devtools::install_github('rstudio/leaflet')
devtools::install_github('bhaskarvk/leaflet.extras')
```

Finally if you still have errors please post the error message in this issue. Please don't forget to format the output as code.

Also include output of `sessionInfo()`

**Comment by WandaB** [comment]
Hi, sorry but I am not too sure how ot format it as code here...

This is what I get after: 

devtools::install_github('rstudio/httpuv')
Skipping install of 'httpuv' from a github remote, the SHA1 (bf8ef78f) has not changed since last install.
  Use `force = TRUE` to force installation

devtools::install_github('rstudio/leaflet')
Downloading GitHub repo rstudio/leaflet@master
from URL https://api.github.com/repos/rstudio/leaflet/zipball/master
Installing leaflet
Downloading GitHub repo rstudio/crosstalk@master
from URL https://api.github.com/repos/rstudio/crosstalk/zipball/master
Installing crosstalk
"C:/Users/Wanda/DOCUME~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Wanda/AppData/Local/Temp/RtmpiYTfdI/devtools25e024cc48c1/rstudio-crosstalk-6a36da1"  \
  --library="C:/Users/Wanda/Documents/R/R-3.3.2/library" --install-tests 

* installing *source* package 'crosstalk' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'xtable'
ERROR: lazy loading failed for package 'crosstalk'
* removing 'C:/Users/Wanda/Documents/R/R-3.3.2/library/crosstalk'
Error: Command failed (1)

devtools::install_github('bhaskarvk/leaflet.extras')
Downloading GitHub repo bhaskarvk/leaflet.extras@master
from URL https://api.github.com/repos/bhaskarvk/leaflet.extras/zipball/master
Installing leaflet.extras
"C:/Users/Wanda/DOCUME~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Wanda/AppData/Local/Temp/RtmpiYTfdI/devtools25e04b8405a/bhaskarvk-leaflet.extras-3558bfe"  \
  --library="C:/Users/Wanda/Documents/R/R-3.3.2/library" --install-tests 

* installing *source* package 'leaflet.extras' ...
** R
** inst
** preparing package for lazy loading
Error : package 'leaflet' 1.0.1 was found, but >= 1.0.2.9008 is required by 'leaflet.extras'
ERROR: lazy loading failed for package 'leaflet.extras'
* removing 'C:/Users/Wanda/Documents/R/R-3.3.2/library/leaflet.extras'
Error: Command failed (1)`

**Comment by WandaB** [comment]
[sessionInfo.txt](https://github.com/bhaskarvk/leaflet.extras/files/711144/sessionInfo.txt)

**Comment by bhaskarvk** [comment]
OK Cool thanks for the outputs. You can format them as code using 3 backticks before and after the text (I already did it for you).

Looks like the issue you are having is w/ crosstalk. 

Could you try 
```r
install.packages(c('xtable','crosstalk'), dependencies=T)
```

 and if you get errors, please file an issue w/ the crosstalk repo [here](https://github.com/rstudio/crosstalk). Lastly sorry this is taking so long for you to resolve but this is outside my control.

**Comment by bhaskarvk** [comment]
Any progress ? I'm closing this as this is not related to installing leaflet.extras, but installing leaflet from github.
