### ISSUE TITLE
input$map_draw_created_features returns NULL

### ISSUE THREAD

**Issue by cclymer** [bhaskarvk/leaflet.extras#52]
I have added the **addDrawToolbar** to my R Shiny leaflet map and am trying to capture the the coordinates of a drawn rectangle. However, the **input$map_draw_created_features** call returns **NULL**. When I edit the drawn rectangle and save it the **input$map_draw_edited_features** returns the expected geojson. I believe I saw a closed issue stating these were both incorporated into leaflet.extras. Please advise.
Thank you,
 Carlee

**Comment by bhaskarvk** [comment]
That should not happen. Could you provide a minimal reproducible sample app?

**Comment by timelyportfolio** [comment]
@cclymer, see if this simplified contrived example works

```r
library(leaflet)
library(leaflet.extras)
library(shiny)

ui <- leafletOutput("leafmap")

server <- function(input, output, session) {
  output$leafmap <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      addDrawToolbar(editOptions = editToolbarOptions())
  })
  
  observeEvent(input$leafmap_draw_new_feature,{
    print(input$leafmap_draw_new_feature)
  })
}

shinyApp(ui, server)
```

**Comment by cclymer** [comment]
Yes, using input$map_draw_new_feature works perfectly, thank you. Is input$map_draw_created_features no longer used?

**Comment by timelyportfolio** [comment]
@cclymer looks like `draw_all_features` is also available ([lines](https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/htmlwidgets/lib/draw/draw-bindings.js#L142-L143)) but I do not see `draw_created_features`.  Looks like since @bhaskarvk added into `leaflet.extras` it has been this way https://github.com/bhaskarvk/leaflet.extras/commit/f1cc1ae8beec8e5be09a58d5e8a7ceb644d9e306#diff-6b788f75a9007fb76ddd2314c8979efc.

**Comment by bhaskarvk** [comment]
Yes I gave them different names and also the way the returned object works. I was not entirely satisfied with the names used in the draw branch of leaflet.
I'll add @timelyportfolio supplied example along with other events to the examples folder for future reference and also update the docs accordingly.

Thanks @timelyportfolio

**Comment by cclymer** [comment]
Thanks for the quick responses. Thanks @timelyportfolio for getting me up and running and @bhaskarvk thank you for your work on this. I look forward to some additional examples!

**Comment by bhaskarvk** [comment]
https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/examples/draw-events/app.R

example shiny app w/ all events that draw can emit. TY @timelyportfolio for starter code!

**Comment by ldfreight** [comment]
Hi @bhaskarvk 
your last link is dead, was it moved to another location?
Thank you
