### ISSUE TITLE
clearShapes and clearMarkers doesn't work

### ISSUE THREAD

**Issue by Eltisho** [bhaskarvk/leaflet.extras#55]
Hi!

I'm doing a survey with Shiny on R where people have to draw polygons and markers on a map to show where they sampled. People fill the form for each sampling campaign (one page per sampling campaign) they did, and can navigate between these pages. 

I create an erase button so people can erase on campaign if they did a mistake. The campaign is erased in "responses" and the form is reset, but the map doesn't update even if I use clearMarkers and clearShapes.

Here is my code:

output$map <- renderLeaflet({
        leaflet() %>% addProviderTiles() %>% setView(1010, 54, 5) %>% 
        addDrawToolbar(**targetGroup = rv$page**, polygonOptions = drawPolygonOptions(),
            markerOptions = drawMarkerOptions(), editOptions = editToolbarOptions(),
            polylineOptions = FALSE, circleOptions = FALSE, rectangleOptions = FALSE)

########### ERASE FORM 
    observeEvent(input$erase, {
        
      if (rv$page < length(responses)) {
        responses[[rv$page]] <<- NULL
        rv$page <- length(responses) + 1
        reset("formulaire")
        #leafletProxy("map") %>% clearShapes() %>% clearMarkers()
      **} else {
        responses[[rv$page]] <<- NULL
        reset("formulaire")
        leafletProxy("map") %>% clearShapes() %>% clearMarkers()
        }
      })**

When rv$page < length(responses), it works because rv$page change so the targetGroup change too.

responses is a list with all the answers.

I hope it's clear, i'm not sure ahah
Thank you!

**Comment by bhaskarvk** [comment]
Thanks for the issue. Could you create a minimally reproducible shiny app that I can run?

**Comment by Eltisho** [comment]
library("shiny")
library("leaflet")
library("leaflet.extras")
library("shinyjs")

shinyApp(
  ui = fluidPage(
    sidebarLayout(position = "right",
                  sidebarPanel(useShinyjs(),
                  actionButton("prev", label = "Previous"),
                  actionButton("nxt", label = "Next"),
                  actionButton("add", label = "Add a campaign"),
                  actionButton("erase", label = "Erase this campaign")
                  ),
    mainPanel(leafletOutput("map"))
    )
  ),
  
  server = function(input, output, session){
    
    ######### INITIALIZE #########
    
    # Create responses if it doesn't exist
    if (!exists("responses"))
      responses <<- list()
    
    output$map <- renderLeaflet({
      leaflet() %>% addTiles() %>%  
        addDrawToolbar(targetGroup = rv$page, polygonOptions = drawPolygonOptions(),
                       markerOptions = drawMarkerOptions(), editOptions = editToolbarOptions(),
                       polylineOptions = FALSE, circleOptions = FALSE, rectangleOptions = FALSE)
    })
    
    # Page count
    rv <- reactiveValues(page = 1)
    
    # Disable/enable prev, next and observe rv$page
    observe({
      toggleState(id = "prev", condition = rv$page > 1)
      toggleState(id = "nxt", condition = rv$page <= length(responses))
      toggleState(id="erase",condition = rv$page > 0 & rv$page < (length(responses)+1))
    })
    
    ######### ADD button behaviour
    
    observeEvent(input$add, {
      
      # if there is no campaign added
      if (length(responses) == 0) {
        
        responses[[length(responses)+1]] <<- input$map_draw_all_features
        
        # go to next page
        rv$page <- rv$page + 1
        
        # reset form
        reset("formulaire")
        
      } else {
        
        responses[[length(responses) + 1]] <<- input$map_draw_all_features
        
        # go to next page
        rv$page <- length(responses) + 1
        
        # reset form
        reset("formulaire")
      }
    })
    
    ######### PREVIOUS prev button behaviour
    observeEvent(input$prev, {
      
      # go to previous page
      rv$page <- rv$page - 1
      
      # Update map
      leafletProxy("map") %>% addGeoJSON(responses[[rv$page]])
      
    })
    
    ######### NEXT button behaviour
    observeEvent(input$nxt, {
      
      # go to next page
      rv$page <- rv$page + 1
      
      if (rv$page <= length(responses)) {
        
        # update map
        leafletProxy("map") %>% addGeoJSON(responses[[rv$page]])
      } else {
        # reset form to have a blank page
        reset("formulaire")
        geo_ref <- NULL
      }
    })
    
    ########### ERASE FORM 
    observeEvent(input$erase, {
      
      if (rv$page < length(responses)) {
        responses[[rv$page]] <<- NULL
        rv$page <- length(responses) + 1
        reset("formulaire")
      } else {
        responses[[rv$page]] <<- NULL
        reset("formulaire")
        leafletProxy("map") %>% clearShapes() %>% clearMarkers()
      }
    })
  }
)

**Comment by Eltisho** [comment]
Sorry it's not taht muc minimally reproducible, but I remove a lot of things. So when I erase a page that is not the last one (rv$page < length(responses)), there is no problem. But when I erase the last form that has been save (rv$page = length(responses)), it doesn't update.

**Comment by bhaskarvk** [comment]
The latest draw plugin has a button to clear the entire layer. I'll soon upgrade to it and then you'll have that option.

**Comment by bhaskarvk** [comment]
I upgraded the draw plugin, the delete button now has an option to clear all drawn features, so you don't need any extra code for that.
