### ISSUE TITLE
Wish: Enable leaflet plug-in Leaflet Coordinates Control

### ISSUE THREAD

**Issue by ricobert1** [bhaskarvk/leaflet.extras#56]
A nice plug-in built for Leaflet: Captures mouseclick and displays its coordinates with easy way to copy them.  https://github.com/zimmicz/Leaflet-Coordinates-Control

**Comment by bhaskarvk** [comment]
`mapview::addMouseCoordinates` should give you the same thing. I am not inclined to duplicate this as it's already available in mapview.
https://github.com/r-spatial/mapview/blob/develop/R/addMouseCoordinates.R#L44
