### ISSUE TITLE
whish: summary by proportion on heatmaps

### ISSUE THREAD

**Issue by Athospd** [bhaskarvk/leaflet.extras#60]
Hello,

In heatmaps we sum up values (passed to intensity argument) over a neibourhood. I would like to be able to aggregate these values with a summary function other than 'sum', for example a proportion of the sum of two variables (eg. sum(x1)/sum(x2), inside the neibourhood).

Is it possible?

Thank you and congratulations for your package!
Regards,
Athos.

**Comment by bhaskarvk** [comment]
You should raise this on the original [Leaflet.heat](https://github.com/Leaflet/Leaflet.heat) repo. That's the plugin I'm using and it does the calculations internally.
