### ISSUE TITLE
Leaflet.draw  : removeDrawToolbar(clearFeatures = TRUE) doesn't work

### ISSUE THREAD

**Issue by RCura** [bhaskarvk/leaflet.extras#61]
Hi,
the `clearFeatures` option doesn't seems to work at all.
When drawing features and removing the draw toolbar, the drawn items remains on the map.

Here's a MRE :

    library(shiny)
    library(leaflet)
    library(leaflet.extras)

    ui <- fluidPage(
      leafletOutput("map"),
      actionButton("rmDraw", "remove Draw toolbar")
    )

    server <- function(session, input, output){
      output$map <- renderLeaflet(
        leaflet() %>%
          addDrawToolbar(targetGroup = "test")
      )
      
      observeEvent(input$rmDraw, {
        proxy <- leafletProxy("map")
        proxy %>%
          removeDrawToolbar(clearFeatures = TRUE)
      })
    }

    shinyApp(ui = ui, server = server)

Run the app, draw any shape, and then click on the actionButton : the toolbar disappears, but the shapes don't :)

**Comment by bhaskarvk** [comment]
Hmm, that shouldn't happen. Thanks for reporting.

**Comment by RCura** [comment]
Trying to fix this, I'll add a PR if I succeed.
I'll also send another PR for a simple feature add, allowing to keep only one drawn item at a time, which is very much easier for using Leaflet.draw as a simple spatial selection tool.
