### ISSUE TITLE
wish: make objects created with Leaflet.Draw accessible in shiny

### ISSUE THREAD

**Issue by dmlee8215** [bhaskarvk/leaflet.extras#66]
It would be super useful if e.g. a polygon created on a leaflet/shiny map after invoking addDrawToolbar could be used in other parts of the app, though something like input$MAPID_shape_click.  Thanks for your work on leaflet.extras, this functionality is awesome!

**Comment by bhaskarvk** [comment]
They already are. Check https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/examples/shiny/draw-events/app.R
