### ISSUE TITLE
[question] How to retrieve coordinates of a drawn polygon / rectangle

### ISSUE THREAD

**Issue by fbaffie** [bhaskarvk/leaflet.extras#67]
Hi,

I had been using the custom fork of leaflet by "RCura" to draw polygons and rectanges. In Shiny, I was able to retrieve the point coordinates of those polygon / rectangles this way:
`selected_stations_indices <- reactive(which_station_in_polygon(stations, input$map_selectbox_features$features))`
and then in the which_station_in_polygonfunction, for each point i in each polygon p:
`coord[i, ] <- c(map_selection[[p]]$geometry$coordinates[[1]][[i]][[1]], map_selection[[p]]$geometry$coordinates[[1]][[i]][[2]])`

I just can't figure it out with "leaflet.extras". Only drawing seems to be documented and not the retrieval of drawn information.
Even `input$map_selectbox_features` doesn't work

Thanks for your help!

**Comment by timelyportfolio** [comment]
If I understand correctly, we are attempting to address this in [`mapedit`](https://github.com/r-spatial/mapedit).  We would love feedback.

**Comment by bhaskarvk** [comment]
https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/examples/shiny/draw-events/app.R has all the event code that you can use for getting back drawn stuff.
I am working on better documenting leaflet.extras, but it's a slow progress.

**Comment by fbaffie** [comment]
Thanks a lot, sorry I hadn't found it by myself!

**Comment by bhaskarvk** [comment]
Also to @timelyportfolio's point, I think mapedit is something you need to look into if you are going to do a lot of drawing and editing. It's being written explicitly for that, while `leaflet.extras` provides the necessary underlying low level support.
