### ISSUE TITLE
Extract coordinates from addControlGPS

### ISSUE THREAD

**Issue by claire-roberts** [bhaskarvk/leaflet.extras#68]
I'm wondering if it's possible to extract the geolocated coordinates from this function?

I've tried
ui.R
verbatimTextOutput("coords")

server.R
output$coords <- renderPrint({
    input$coordinates
  })
 
It just printed NULL

Thanks!

**Comment by bhaskarvk** [comment]
When a location is found a Shiny event `map.id+'_search_location_found'` is emitted.
https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/htmlwidgets/lib/search/leaflet-search-binding.js#L31
You can catch that Shiny event as described https://rstudio.github.io/leaflet/shiny.html
