### ISSUE TITLE
fullscreen button not working on IOS Iphone

### ISSUE THREAD

**Issue by jp1312** [bhaskarvk/leaflet.extras#69]
Hi,

thanks for these amazing extras! I tested the fullscreen button while building a leaflet in R using

` myLeaflet %>% addFullscreenControl()
`

I am embedding the map in my site using iframe

`<iframe style="border: 0;" src="http://slow-data.com/webmap/openmap.html" width="3000" height="450" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
`

the page with iframe is this one http://slow-data.com/wifibar/
on desktop the fullscreen button works great and on Android too, but on my Iphone 5 it doesn't. Any idea what is going on?

Thanks,
Jacopo

**Comment by bhaskarvk** [comment]
Try with the pseudo full screen mode.
`addFullscreenControl(pseudoFullscreen = TRUE)`

If you want a test page see http://rpubs.com/bhaskarvk/fullscreen second example.
If pseudo full screen mode works for you, please add a comment for future reference and close the issue.

**Comment by jp1312** [comment]
I tested and it doesn't work. In addition with this option also full screen on desktop does not work.

**Comment by bhaskarvk** [comment]
Another point 
`allowfullscreen="allowfullscreen"`

should be just `allowfullscreen`, so something like `<iframe ... allowfullscreen>`

**Comment by jp1312** [comment]
Yes, but my CMS (wordpress) changes automatically to allowfullscreen="allowfullscreen". I don't know why. Do you think this could be the problem?

**Comment by bhaskarvk** [comment]
I don't know. Did you try the second example in http://rpubs.com/bhaskarvk/fullscreen in iphone5 ? Does it work ?

**Comment by bhaskarvk** [comment]
I don't know. Does the second example from my link above work in iphone 5.x ?

**Comment by bhaskarvk** [comment]
Nothing more to do from leaflet.extra's side. Something to be investigated on iphone browser side.

**Comment by zhen1991** [comment]
Hi guys!
I am facing the same problem,so i am wondering if you guys found a solution to this??
thnx for helping !
by the way my map is only not working on safari in iphone but it work on safari in mac!
