### ISSUE TITLE
Deselect point after searching

### ISSUE THREAD

**Issue by LuukTX** [bhaskarvk/leaflet.extras#70]
Hello,

I added a search marker to my leaflet map using your leaflet.extras-package. I used the following code:

%>% addSearchMarker(targetGroup = "stations",options = searchMarkersOptions(openPopup=T)

After I search for a data point, this data point is selected and highlighted. However, I can't deselect this data point after searching. Is there a way to deselect selected points after searching?

Thanks in advance!

**Comment by bhaskarvk** [comment]
I will need to do some research on this. Stay tuned!

**Comment by bhaskarvk** [comment]
Duplicate of #95. See solution posted in that issue.
