### ISSUE TITLE
Missing dependencies: packages crosstalk, Rccp, httpuv, xtable

### ISSUE THREAD

**Issue by markdumke** [bhaskarvk/leaflet.extras#71]
When I try to install the **leaflet.extras** package using `devtools::install_github()` in a fresh R installation without any packages preinstalled other than the base packages  I get the following errors:

```
 there is no package called 'crosstalk'
 there is no package called 'Rccp'
 there is no package called 'httpuv'
 there is no package called 'xtable'
```

When I install these manually the installation works. It's probably best to include these four packages into the `Imports` section in the `DESCRIPTION` file as otherwise the installation will fail and the user will have to manually install these four packages.

**Comment by bhaskarvk** [comment]
It's the leaflet package that depends on these 4 and leaflet.extras depends on leaflet. But in any case this error should not happen. Thanks for reporting.

**Comment by bhaskarvk** [comment]
I am closing this. This should not happen and this package doesn't directly depend on any of these packages so I don't want to add them to the DESCRIPTION file. I will investigate more if others have similar issues. Also now that the package is on CRAN, devtools::install_github is no longer needed except for dev purposes.
