### ISSUE TITLE
wish: add Pie chart as marker on map

### ISSUE THREAD

**Issue by kuzmenkov111** [bhaskarvk/leaflet.extras#73]
There are (https://github.com/humangeo/leaflet-dvf) Leaflet DVF and https://github.com/sashakavun/leaflet-piechart extension which make possible to add pie charts on map. Is it possible to to add this extention to leaflet.extras?

**Comment by jz1584** [comment]
+ 1 It's would be great if it's available

**Comment by tim-salabim** [comment]
how bout https://github.com/rte-antares-rpackage/leaflet.minicharts?

**Comment by kuzmenkov111** [comment]
Already use!

**Comment by bhaskarvk** [comment]
Closing due to availability of leaflet.minicharts pkg.
