### ISSUE TITLE
Wish: Datatable records linked to markers/polygons on a leafletmap

### ISSUE THREAD

**Issue by BilboBaagins** [bhaskarvk/leaflet.extras#74]
Hi there. 

I wonder if it would be possible to have a package/plugin that allows the user to create a datatable (from the underlying data that is used to produce a leaflet map) and link it to markers/polygons on the map. 

For example, when you click on a record in the datatable, it would highlight/zoom-to the corresponding polygon on the map. 
Also, visa/versa if you click on a polygon on the map, it highlights/selects that record in the datatable. 

I am aware of the [SuperZip example](http://shiny.rstudio.com/gallery/superzip-example.html) using Shiny, however this is not a viable option for me. 

I have also come across [leaflet.table](http://diogok.github.io/leaflet.table/) on GitHub, which seems to do  the trick. 

I have managed to create a leaflet map and a datatable in a RMarkdown document so far but they are not linked. I wonder is there also a way to link the two using HTML/Javascript after the widgit has been built.

Thanks

**Comment by bhaskarvk** [comment]
Take a look at rstudio/crosstalk, it is designed exactly for that purpose.

**Comment by BilboBaagins** [comment]
Thanks for pointing me in the right direction. 

I can't seem to get a SpatialPolygonDataFrame to link with the Datatable but SpatialPoitnsDF works fine. I am aware of the issue [#406](https://github.com/rstudio/leaflet/issues/406) in rstudio/leaflet/issues that crosstalk is only working for point data at the moment and polygon support is coming. 

I am just wondering if it is possible as is done in [this Gapminder example](https://rstudio-pubs-static.s3.amazonaws.com/215948_95c1ab86ad334d2f82856d9e5ebc16af.html) ?
The line that is giving me an error is when `sd` is a SpatialPolygonDF and I try to link it to the datatable as in the Gapminder example using `sd$transform(as.data.frame)`.

This is the error I get **Error in inherits(x, "SharedData") : attempt to apply non-function**. 

Any help regarding this would be much appreciated. Thanks very much - it's a super looking package.

**Comment by bhaskarvk** [comment]
Could you open this defect with a reproducible code on the leaflet repo ? That way it's better to track it.

**Comment by BilboBaagins** [comment]
Hi bhaskarvk, 

I have opened this as a new issue with reproducible code https://github.com/rstudio/leaflet/issues/423.

Hopefully it's what you're looking for. 
Cheers,
