### ISSUE TITLE
Shiny input associated with search doesn't show up in list of inputs

### ISSUE THREAD

**Issue by doug-friedman** [bhaskarvk/leaflet.extras#76]
When I use the `addSearchOSM` function with leaflet (and leaflet.extras) in a Shiny application I cannot find [the Shiny input you've bound to the location search results](https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/htmlwidgets/lib/search/leaflet-search-binding.js#L31).

Here's a simple example where I constantly print the available inputs to the R console. Ideally, I should be able to access `input$leaf_search_location_found`.

```R
library(shiny)
library(leaflet)
library(leaflet.extras)


ui = fluidPage(
  leafletOutput("leaf")
)

server = function(input, output){

  output$leaf =  renderLeaflet({
    breweries91 %>%
      leaflet() %>%
      addTiles() %>%
      addMarkers() %>%
      addSearchOSM()
  })

  observe({
    print(names(input))
  })

}

shinyApp(ui=ui, server=server)


```

**Comment by bhaskarvk** [comment]
Instead of your observe code try this

```r
observeEvent(input$leaf_search_location_found,{
    print(input$leaf_search_location_found)
  })
```

**Comment by bhaskarvk** [comment]
Closing with the correct code provided. reopen if this doesn't work.
