### ISSUE TITLE
Antimeridian cutting on the fly while rendering with addGeoJSONv2 possible?

### ISSUE THREAD

**Issue by TrantorM** [bhaskarvk/leaflet.extras#79]
The following example shows the problem with the horizontal lines while rendering a polygon over the antimeridian. Is it possible to get rid of this problem in the addGeoJSONv2 function? Maybe with an 'on the fly' antimeridian cutting.

```
library(leaflet) 
library(leaflet.extras)

SolarEclipsePolygons.geojson <- readr::read_file('https://rawgit.com/TrantorM/topojson-data/master/EclipsePolygons.geojson')

leaflet() %>% addProviderTiles("CartoDB.Positron") %>% addGeoJSONv2(SolarEclipsePolygons.geojson,weight =1)
```

**Comment by bhaskarvk** [comment]
Related to this https://github.com/Leaflet/Leaflet/issues/2868, I'll see if it can be avoided.

**Comment by bhaskarvk** [comment]
I don't think this can be done so easily in addGeoJSONv2. You will have to manually do that in the geojson, here's an approach for CartoDB https://carto.com/blog/jets-and-datelines.

**Comment by TrantorM** [comment]
Yes, that's what I thought too, that it can't be done so easily. I just saw [this in D3](https://bl.ocks.org/mbostock/3788999). Thanks anyway.
