### ISSUE TITLE
Heatmap zooming 

### ISSUE THREAD

**Issue by kezhan** [bhaskarvk/leaflet.extras#8]
Hello, thank you very much for these extra features. In particular, I am interested in heatmaps. I succeeded to create heatmaps by using `addWebGLHeatmap` function. However, I noticed that while zooming in, the heatmap doesn't change. (the size parameter determines how we see the heatmap.)
I found this page http://rmaps.github.io/blog/posts/leaflet-heat-maps/index.html, and it is possible to create one that displays more detailed heatmap when zooming in. 
I was wondering if it is possible to do some modifications to take this into account.

**Comment by bhaskarvk** [comment]
Did you try with units='px'.
See http://rpubs.com/bhaskarvk/leaflet-heatmap, there I've both examples where the size is constant and when it varies as you zoom in/out.

**Comment by kezhan** [comment]
Thank you for your reply. It works perfectly.
