### ISSUE TITLE
wish: leaflet.wms GetFeatureInfo

### ISSUE THREAD

**Issue by Arevaju** [bhaskarvk/leaflet.extras#84]
Plugin for Leaflet WMS GetFeatureInfo request:  https://github.com/heigeo/leaflet.wms
Thanks

**Comment by bhaskarvk** [comment]
The plugin only works under leaflet 1.x JS, while leaflet R package still uses 0.7.x. I will integrate the plugin as soon as leaflet moves to 1.x.

**Comment by rickyars** [comment]
Any clue when leaflet will move to 1.x?

**Comment by bhaskarvk** [comment]
There's already some work in progress for that https://github.com/rstudio/leaflet/issues/357

**Comment by bhaskarvk** [comment]
Closing for now. Feel free to reopen when Leaflet goes to 1.x

**Comment by aTnT** [comment]
Has `GetFeatureInfo` been implemented? This seems to be a highly requested feature (see https://gis.stackexchange.com/questions/334004/enable-wms-getfeatureinfo-request-in-leaflet-using-r)

**Comment by trafficonese** [comment]
I started implementing this plugin in `leaflet.extras2`. You can find it here: https://github.com/trafficonese/leaflet.extras2.
It's not on CRAN yet, but I would be happy if you give it a try and tell me if it meets your needs.

**Comment by aTnT** [comment]
Thanks @trafficonese for the `leaflet.extras2` package, this is great work! The `GetFeatureInfo` feature works well! The only small detail (probably unrelated to the `leaflet.extras2::addWMS()` function) is that i cannot control the popup box size (see picture below). I have tried unsuccessfully to change A and B within `popupOptions(maxWidth = A, minWidth = B)`.

![image](https://user-images.githubusercontent.com/3149376/80216474-03e64500-8636-11ea-973a-da9a3f8cdfe4.png)

**Comment by trafficonese** [comment]
Thank you! I'm glad you find it useful!
I just pushed a commit, which includes the `popupOptions` argument for `addWMS`, so you should be able to include `popupOptions = popupOptions(maxWidth = 600)` for example.
I also included [another example](https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/wms_popup.R) which does just that.

**Comment by aTnT** [comment]
Thanks again @trafficonese, it works now! :)

![image](https://user-images.githubusercontent.com/3149376/80241127-fa230880-865a-11ea-819b-bbbd3ed6667a.png)

**Comment by MoritzMennenga** [comment]
Dear @trafficonese I'd I tried around a lot, but I doenst't work in my case. I tried it with my data first and then I used your example [https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/wms_popup.R](https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/wms_popup.R). If I use `leaflet.extras2::addWMS()` there is no WMS displayed. If I use the same with `addWMSTiles` (and without the popup) I can see the WMSmap but I can't use the popup Feature for the getFeatureInformation I really need.

**Comment by trafficonese** [comment]
Could you please open an issue here https://github.com/trafficonese/leaflet.extras2/issues and include your `sessioninfo::session_info()`? It works for me, but I am still on leaflet '2.0.1'
