### ISSUE TITLE
drawRectangeOptions missing "L"

### ISSUE THREAD

**Issue by timelyportfolio** [bhaskarvk/leaflet.extras#86]
Since this is pervasive, I chose an issue instead of inline comment.  I think `drawRectangeOptions` should be `drawRectangleOptions`.  I am happy to submit a pull if it is helpful.

I think you know how much I appreciate your work here, but if not Thanks Again!

**Comment by bhaskarvk** [comment]
I will fix it later this week.

**Comment by bhaskarvk** [comment]
Fixed in dbfa4cd
