### ISSUE TITLE
prep for CRAN initial release

### ISSUE THREAD

**Issue by timelyportfolio** [bhaskarvk/leaflet.extras#87]
`leaflet.extras` would be even awesomeR if on CRAN.  If possible, I would love to see it hit CRAN before useR 2017, which would also mean [`mapedit`](https://github.com/r-spatial/mapedit) could release prior to useR.  I will volunteer to do the early prep work and track at [forked branch](https://github.com/timelyportfolio/leaflet.extras/tree/cran).

### checklist from CRAN check

- [x] reduce size < 5mb
      [treemap](https://bl.ocks.org/timelyportfolio/fb7e81130770089c4f31a4a937f838cf)
      [sunburst](https://bl.ocks.org/timelyportfolio/69a70ead46ebbb832c8d3114113e024f)
      * rbuildignore virginia.rds - delete? https://github.com/timelyportfolio/leaflet.extras/commit/4a41a625dca917ef1bf2c3928fc9200531ed40a1
      * delete mapshaper.js and turf.js since I see no dependencies on these https://github.com/timelyportfolio/leaflet.extras/commit/25d706e9b17f201316c30d9bc329145d2e52da8b
- [x] undocumented arguments https://github.com/timelyportfolio/leaflet.extras/commit/11762c775ffb0a441d327bad1058c781e01983b9

cc @tim-salabim

**Comment by timelyportfolio** [comment]
After completing the checklist above, passes local CRAN check and `rhub::check_for_cran()`.

**Comment by bhaskarvk** [comment]
Working on this now, will submit to CRAN before EOD. Thanks so much for taking a lead on this.

**Comment by bhaskarvk** [comment]
Submitted to CRAN. Fingers crossed!
