### ISSUE TITLE
[feature request] Bing.js plugin

### ISSUE THREAD

**Issue by tim-salabim** [bhaskarvk/leaflet.extras#91]
As discussed at UseR!2017 here is the feature request for supporting bing tiles. The relevant js lib is here
https://github.com/shramov/leaflet-plugins/blob/v2/layer/tile/Bing.js

I dare not ask, but do you think this could be implemented within a few weeks?

**Comment by bhaskarvk** [comment]
Next week for sure.

**Comment by tim-salabim** [comment]
Awesome!

**Comment by tim-salabim** [comment]
Any news on this?

**Comment by bhaskarvk** [comment]
Yup working on it. Should be done by mid next week.

**Comment by bhaskarvk** [comment]
Bing Layer support is now in trunk. Unfortunately looks like Birdseye views are not supported. I will take them out of the permitted options. See https://github.com/shramov/leaflet-plugins/issues/58
