### ISSUE TITLE
Feature Request drop down filter

### ISSUE THREAD

**Issue by dmaupin12** [bhaskarvk/leaflet.extras#94]
I believe it's possible to add a drop down filter in js. Anyway we could add this to r leaflet?

**Comment by bhaskarvk** [comment]
Link to a demo or JS lib?

**Comment by bhaskarvk** [comment]
Closing as no further response. Feel free to reopen with concrete example of what you exactly want.

**Comment by dmaupin12** [comment]
Sorry for the delay, 

see the link for a demo. 

http://jsfiddle.net/nFLc3/

**Comment by bhaskarvk** [comment]
Yeah this should be easily doable even with just the core leaflet pkg. I will upload a sample soon.

**Comment by dmaupin12** [comment]
Awesome! Thanks for your help.

**Comment by dmaupin12** [comment]
Just curious, have you been able to figure out a way to add the dropdown bar?

**Comment by bhaskarvk** [comment]
end of this week, I promise

**Comment by dmaupin12** [comment]
I know your super busy, but i just wanted to check and see if the drop down filter could be implemented? Also, do i need to learn javascript in order to add adaptations such as the filter to the leaflet r package? 

Thanks
