### ISSUE TITLE
addSearchMarker

### ISSUE THREAD

**Issue by rhaefer** [bhaskarvk/leaflet.extras#95]
Is there a way to disable the small red circle that appears when you use the addSearchMarker function and zoom to a feature?

**Comment by bhaskarvk** [comment]
I don't know, I'll have to research.

**Comment by bhaskarvk** [comment]
In `searchMarkerOptions()` pass `hideMarkerOnCollapse = TRUE`

When you search you'll still see the red marker, but you can clear the search box and collapse it by clicking the magnifying glass again, and this will get rid of the red circle. I am not aware of any other way to do it.

https://github.com/stefanocudini/leaflet-search/issues/132
