### ISSUE TITLE
Adding support for leaflet-geosearch plugin?

### ISSUE THREAD

**Issue by smach** [bhaskarvk/leaflet.extras#97]
It would be great to be able to add address searching to an R Leaflet map -- address autocomplete and then zooming to the address when it's searched. The[ leaflet-geosearch plugin](https://github.com/smeijer/leaflet-geosearch) does this, [live examples here](https://smeijer.github.io/leaflet-geosearch/#openstreetmap).

This would be very useful for a public service project showing a city's new voting districts, so people could see where they vote and who their local candidates are. You can see an [early version of this project here](http://district2framingham.com/mapinprogress.html).

**Comment by bhaskarvk** [comment]
Thanks Sharon. There is already geolocating support via the leaflet search plugin. The `addSearchOSM()` function allows you to geolocate using OSM API. Does that work for you?

**Comment by smach** [comment]
Thank you. I may not understand the full capabilities of that plugin. I saw that and looked at the examples, and it seemed to me that it could only search already-defined features on a map, or perhaps a street but not a specific address. Am I wrong? Can it be used to add a street-address search that would zoom in on an address on the leaflet map?

**Comment by bhaskarvk** [comment]
I do need to spend some time on documenting all the features of leaflet.extras :)

**Comment by smach** [comment]
If I figure out how to do what I want with leaflet.extras, I'll write it up for Computerworld and you can link to it! :-) By the way, I'm also going to investigate returning which district a geocoded location is in, using the [Wherewolf JavaScript library](https://github.com/veltman/wherewolf). That would be a cool addition!  

Tyler Dukes told me that [this WRAL North Carolina district lookup](http://www.wral.com/news/state/nccapitol/page/14375698/) was made with Leaflet.js (not the R version) and Wherewolf.js.

**Comment by bhaskarvk** [comment]
Oh wherewolf looks very interesting. I must add it into leaflet.extras. Thanks for pointing me to it.

**Comment by smach** [comment]
That. Would. Be. Awesome. R-using journalists would find that very compelling. THANKS!!!

**Comment by smach** [comment]
It's very possible I'm missing something, but when I add addSearchOSM() to my Leaflet map, it only searches for streets but not _exact addresses_. So, a search finds an address _approximately_ on the street, but not exactly at the address property, and the marker sometimes ends up blocks away. That's a problem for a precinct map, because streets cross precinct boundaries. For this purpose, I would need more exact address geocoding that's available from the geosearching plugin I mentioned at the beginning. (But meanwhile I'll live without it and just let people find their locations).

**Comment by bhaskarvk** [comment]
Thanks for the report @smach. I will need to investigate whether this is the limitation of the OSM API or if the leaflet-search plugin. In the mean time, I am also adding support for google geocoding so stay tuned. If we can't have any success with either OSM or Google in terms of accuracy, then I will surely integrate that other plugin. Although this https://github.com/perliedman/leaflet-control-geocoder plugin supports many more geocoders so I might go with this one.

**Comment by bhaskarvk** [comment]
@smach In the mean time could you give me some sample of address searches which failed.

**Comment by bhaskarvk** [comment]
Just tested out the Google GeoCoder and it seems to resolve street numbers correctly. I will push an update soon.

**Comment by smach** [comment]
That's super! Not sure if you still need samples of address searches that failed, but 680 Old Connecticut Path, Framingham shows in Precinct 9 when it's in Precinct 3 (because all addresses on Old Conn Path show in the same place and the street crosses precinct lines). Note that I just added `leaflet.extras::addSearchOSM()` without any options for addSearchOSM().

**Comment by bhaskarvk** [comment]
Cool, I'll push out a  new version w/ Google Geocoder soon and hopefully it will solve the problem. Note that you need an API key for the Google Geocoder API, but you will need that regardless of which plugin you use. Same for Bing or Esri or other non-OSM providers.

**Comment by bhaskarvk** [comment]
![Imgur](http://i.imgur.com/4ZGTeJd.png)

@smach ,this is what Google Geocoder comes up with. Is this correct as per your assessment ?

**Comment by smach** [comment]
Yes, that's just where the official town map shows it

**Comment by bhaskarvk** [comment]
OK cool, then my next push should be able to resolve your issue.

**Comment by bhaskarvk** [comment]
Pushed new changes with support for Google Geocoder and US Census Bureau Geocoder in addition to OSM. There are some API changes so you to rewrite some of the code.
e.g. http://rpubs.com/bhaskarvk/leaflet-search

**Comment by arthurgailes** [comment]
Is there a way to pass options through to these search commands? Thank you!
