### ISSUE TITLE
Moving markers - feature request

### ISSUE THREAD

**Issue by smartinsightsfromdata** [bhaskarvk/leaflet.extras#99]
I think it would be fantastic to add the plugin below to the range of pluging currently available.

See [**Leaflet.MovingMarker**](https://github.com/ewoken/Leaflet.MovingMarker) and demo reacheble from the page.

=====
Just noticed this is a duplicate of  `support for animated markers` #39 

I will leave this to rise interest in moving markers!

Many thanks to @bhaskarvk  for the great work he's doing for the R community.

**Comment by bhaskarvk** [comment]
I have begun work on time dimension support so expect some movement on these issues soon.

**Comment by bhaskarvk** [comment]
closing as deplicate of #39
